name: Challenge Two, FIGHT!
on:
  pull_request:
    branches: [master]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: - run: echo "Second challenge"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Lin code
        run: npm run lint