name: parallel

on:
  push:
    branches: [ master ] ## Challenge 3
  pull_request:
    branches: [master]

jobs:
  # Cancel Previous Redundant Builds
  challenge-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: log
        run: |
          echo "Hello world"
      - name: log into PR
        if: github.event_name != 'push'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Real State rocks 🕶️!`
            })
  challenge-2:
    runs-on: ubuntu-latest
    needs: [challenge-1]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: challenge-2-install
        run: npm i
      - name: challenge-2-test
        run: npm run test