name: Check code quality
on:
  pull_request:
    branches:
      - master
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
  lint_and_test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
